export const UserData2 = [
    {
      id: 1,
      name: 'Elon Musk',
      username: 'muskelon',
      profile: require('../assets/data/elondp.png'),
      post: {
        id: '14124114',
        image: require('../assets/data/elonpost.png'),
        caption: 'Hi Everyone, Elon musk is here',
        like: 30,
        date: '01/05/2023',
      },
    },
    {
      id: 2,
      name: 'Harsh Beniwal',
      username: 'harsh',
      profile: require('../assets/data/harshdp.png'),
      post: {
        id: '1412',
        image: require('../assets/data/harshp.png'),
        caption: 'hi....',
        like: 25,
        date: '08/04/2023',
      },
    },
    {
      id: 3,
      name: 'Daniella Rahmeh',
      username: 'drahmeh',
      profile: require('../assets/data/modidp.png'),
      post: {
        id: '111',
        image: require('../assets/data/modis.png'),
        caption: '2000 ke note band',
        like: 99,
        date: '12/05/2023',
      },
    },
    {
      id: 4,
      name: 'MaguybouGhosn',
      username: 'mboughsn',
      profile: require('../assets/data/sonamdp.png'),
      post: {
        id: '1432431',
        image: require('../assets/data/sonmp.png'),
        caption: 'carry on jatta',
        like: 88,
        date: '12/05/2023',
      },
    },
    {
      id: 5,
      name: 'Elon Musk',
      username: 'muskelon',
      profile: require('../assets/data/elondp.png'),
      post: {
        id: '24132413',
        image: require('../assets/post2.jpg'),
        caption: 'Another day, another launch!',
        like: 42,
        date: '02/05/2023',
      },
    },
    {
      id: 6,
      name: 'Harsh Beniwal',
      username: 'harsh',
      profile: require('../assets/data/harshdp.png'),
      post: {
        id: '243124',
        image: require('../assets/post3.jpg'),
        caption: 'React Native is awesome!',
        like: 33,
        date: '09/04/2023',
      },
    },
  ];
  
  export const UserData = [
    {
      id: 1,
      name: 'Elon Musk',
      commentsNumber: 253,
      username: 'muskelon',
      profile: require('../assets/data/elondp.png'),
      bio: 'Creator of SpaceX\nTesla CEO\nDogecoin fan',
      story: {
        time: 10,
        image: require('../assets/data/elonstory.png'),
      },
      posts: [
        {
          id: '14124114',
          time: '09:00 AM',
          date: '01/05/2023',
          image: require('../assets/data/elonpost.png'),
          caption: 'Hi Everyone, Elon musk is here',
          like: 30,
          shareCount: 12,
          comments: [
            {
              id: 1,
              text: 'nice one buddy',
              user: {
                id: 2,
                name: 'Harsh Beniwal',
                username: 'harsh',
                profile: require('../assets/data/harshdp.png'),
              },
              time: '2023-05-01T09:05:00Z',
              likes: 4,
              replies: [
                {
                  id: 101,
                  text: 'Thanks!',
                  user: {
                    id: 1,
                    name: 'Elon Musk',
                    username: 'muskelon',
                    profile: require('../assets/data/elondp.png'),
                  },
                  time: '2023-05-01T09:10:00Z',
                  likes: 2,
                },
              ],
            },
            {
              id: 2,
              text: 'What is this?',
              user: {
                id: 3,
                name: 'Daniella Rahmeh',
                username: 'drahmeh',
                profile: require('../assets/data/modidp.png'),
              },
              time: '2023-05-01T09:07:00Z',
              likes: 1,
              replies: [],
            },
          ],
        },
        {
          id: '24132413',
          time: '10:00 PM',
          date: '02/05/2023',
          image: require('../assets/post2.jpg'),
          caption: 'Another day, another launch!',
          like: 42,
          shareCount: 232,
          comments: [
            {
              id: 1,
              text: 'Awesome launch!',
              user: {
                id: 4,
                name: 'MaguybouGhosn',
                username: 'mboughsn',
                profile: require('../assets/data/sonamdp.png'),
              },
              time: '2023-05-02T22:05:00Z',
              likes: 3,
              replies: [
                {
                  id: 102,
                  text: 'Thank you!',
                  user: {
                    id: 1,
                    name: 'Elon Musk',
                    username: 'muskelon',
                    profile: require('../assets/data/elondp.png'),
                  },
                  time: '2023-05-02T22:10:00Z',
                  likes: 1,
                },
              ],
            },
            {
              id: 2,
              text: 'Congrats!',
              user: {
                id: 2,
                name: 'Harsh Beniwal',
                username: 'harsh',
                profile: require('../assets/data/harshdp.png'),
              },
              time: '2023-05-02T22:06:00Z',
              likes: 2,
              replies: [],
            },
          ],
        },
      ],
      messages: [
        {
          id: '1',
          user: {
            username: 'muskelon',
            image: require('../assets/data/elondp.png'),
          },
          lastMessage: 'Hey, did you see the latest SpaceX launch? 🚀',
          time: '1m',
          unread: true,
        },
        {
          id: '2',
          user: {username: 'me', image: require('../assets/CodeBuilder.jpeg')},
          lastMessage: 'Yes! It was incredible! 🔥',
          time: '1m',
          unread: false,
        },
        {
          id: '3',
          user: {
            username: 'muskelon',
            image: require('../assets/data/elondp.png'),
          },
          lastMessage: 'Let’s catch up soon.',
          time: 'now',
          unread: false,
        },
      ],
    },
    {
      id: 2,
      name: 'Harsh Beniwal',
      commentsNumber: 24,
      username: 'harsh',
      profile: require('../assets/data/harshdp.png'),
      story: {
        time: 8,
        image: require('../assets/data/harshs.png'),
      },
      posts: [
        {
          id: '1412',
          time: '04:00 PM',
          date: '08/04/2023',
          image: require('../assets/data/harshp.png'),
          caption: 'hi....',
          like: 25,
          shareCount: 234,
          comments: [
            {
              id: 1,
              text: 'Looking forward to your next video!',
              user: {
                id: 1,
                name: 'Elon Musk',
                username: 'muskelon',
                profile: require('../assets/data/elondp.png'),
              },
              time: '2023-04-08T16:10:00Z',
              likes: 5,
              replies: [
                {
                  id: 201,
                  text: 'Thanks Elon!',
                  user: {
                    id: 2,
                    name: 'Harsh Beniwal',
                    username: 'harsh',
                    profile: require('../assets/data/harshdp.png'),
                  },
                  time: '2023-04-08T16:12:00Z',
                  likes: 1,
                },
              ],
            },
            {
              id: 2,
              text: 'Nice post!',
              user: {
                id: 3,
                name: 'Daniella Rahmeh',
                username: 'drahmeh',
                profile: require('../assets/data/modidp.png'),
              },
              time: '2023-04-08T16:15:00Z',
              likes: 2,
              replies: [],
            },
          ],
        },
        {
          id: '243124',
          time: '05:00 PM',
          date: '09/04/2023',
          image: require('../assets/post3.jpg'),
          caption: 'React Native is awesome!',
          like: 33,
          shareCount: 2,
          comments: [
            {
              id: 1,
              text: 'Agreed! RN is great.',
              user: {
                id: 4,
                name: 'MaguybouGhosn',
                username: 'mboughsn',
                profile: require('../assets/data/sonamdp.png'),
              },
              time: '2023-04-09T17:05:00Z',
              likes: 3,
              replies: [],
            },
            {
              id: 2,
              text: 'Keep it up!',
              user: {
                id: 1,
                name: 'Elon Musk',
                username: 'muskelon',
                profile: require('../assets/data/elondp.png'),
              },
              time: '2023-04-09T17:10:00Z',
              likes: 1,
              replies: [],
            },
          ],
        },
      ],
      messages: [
        {
          id: '1',
          user: {username: 'harsh', image: require('../assets/data/harshdp.png')},
          lastMessage: 'Bro, new video dropping tonight! 🎬',
          time: '5m',
          unread: true,
        },
        {
          id: '2',
          user: {username: 'me', image: require('../assets/CodeBuilder.jpeg')},
          lastMessage: 'Can’t wait to watch it! 😁',
          time: '4m',
          unread: false,
        },
        {
          id: '3',
          user: {username: 'harsh', image: require('../assets/data/harshdp.png')},
          lastMessage: 'Let’s do a collab soon.',
          time: 'now',
          unread: false,
        },
      ],
    },
    {
      id: 3,
      name: 'Daniella Rahmeh',
      commentsNumber: 190,
      username: 'drahmeh',
      profile: require('../assets/data/modidp.png'),
      story: {
        time: 15,
        image: require('../assets/data/sonams.png'),
      },
      posts: [
        {
          id: '111',
          time: '07:00 AM',
          date: '12/05/2023',
          image: require('../assets/data/modis.png'),
          caption: '2000 ke note band',
          like: 99,
          shareCount: 23,
          comments: [
            {
              id: 1,
              text: 'Interesting caption!',
              user: {
                id: 2,
                name: 'Harsh Beniwal',
                username: 'harsh',
                profile: require('../assets/data/harshdp.png'),
              },
              time: '2023-05-12T07:10:00Z',
              likes: 2,
              replies: [
                {
                  id: 301,
                  text: 'Thank you!',
                  user: {
                    id: 3,
                    name: 'Daniella Rahmeh',
                    username: 'drahmeh',
                    profile: require('../assets/data/modidp.png'),
                  },
                  time: '2023-05-12T07:12:00Z',
                  likes: 1,
                },
              ],
            },
            {
              id: 2,
              text: 'Nice post!',
              user: {
                id: 4,
                name: 'MaguybouGhosn',
                username: 'mboughsn',
                profile: require('../assets/data/sonamdp.png'),
              },
              time: '2023-05-12T07:15:00Z',
              likes: 1,
              replies: [],
            },
          ],
        },
        {
          id: '2111',
          time: '08:00 AM',
          date: '13/05/2023',
          image: require('../assets/post4.jpg'),
          caption: 'Coffee time ☕️',
          like: 21,
          shareCount: 12,
          comments: [
            {
              id: 1,
              text: 'Enjoy your coffee!',
              user: {
                id: 1,
                name: 'Elon Musk',
                username: 'muskelon',
                profile: require('../assets/data/elondp.png'),
              },
              time: '2023-05-13T08:05:00Z',
              likes: 2,
              replies: [],
            },
          ],
        },
      ],
      messages: [
        {
          id: '1',
          user: {
            username: 'drahmeh',
            image: require('../assets/data/modidp.png'),
          },
          lastMessage: 'Hey! Are you coming to the shoot tomorrow?',
          time: '10m',
          unread: true,
        },
        {
          id: '2',
          user: {username: 'me', image: require('../assets/CodeBuilder.jpeg')},
          lastMessage: 'Yes, I’ll be there at 9am!',
          time: '9m',
          unread: false,
        },
        {
          id: '3',
          user: {
            username: 'drahmeh',
            image: require('../assets/data/modidp.png'),
          },
          lastMessage: 'Awesome, see you! 😊',
          time: 'now',
          unread: false,
        },
      ],
    },
    {
      id: 4,
      name: 'MaguybouGhosn',
      commentsNumber: 168,
      username: 'mboughsn',
      profile: require('../assets/data/sonamdp.png'),
      story: {
        time: 13,
        image: require('../assets/data/modip.png'),
      },
      posts: [
        {
          id: '1432431',
          time: '07:00 AM',
          date: '12/05/2023',
          image: require('../assets/data/sonmp.png'),
          caption: 'carry on jatta',
          like: 88,
          shareCount: 45,
          comments: [
            {
              id: 1,
              text: 'Great post!',
              user: {
                id: 3,
                name: 'Daniella Rahmeh',
                username: 'drahmeh',
                profile: require('../assets/data/modidp.png'),
              },
              time: '2023-05-12T07:10:00Z',
              likes: 2,
              replies: [],
            },
            {
              id: 2,
              text: 'Love this!',
              user: {
                id: 2,
                name: 'Harsh Beniwal',
                username: 'harsh',
                profile: require('../assets/data/harshdp.png'),
              },
              time: '2023-05-12T07:12:00Z',
              likes: 1,
              replies: [],
            },
          ],
        },
        {
          id: '241241',
          time: '08:00 AM',
          date: '13/05/2023',
          image: require('../assets/post5.jpg'),
          caption: 'Sunshine and smiles!',
          like: 17,
          shareCount: 3,
          comments: [
            {
              id: 1,
              text: 'So bright!',
              user: {
                id: 1,
                name: 'Elon Musk',
                username: 'muskelon',
                profile: require('../assets/data/elondp.png'),
              },
              time: '2023-05-13T08:10:00Z',
              likes: 1,
              replies: [],
            },
            {
              id: 2,
              text: 'Nice photo!',
              user: {
                id: 3,
                name: 'Daniella Rahmeh',
                username: 'drahmeh',
                profile: require('../assets/data/modidp.png'),
              },
              time: '2023-05-13T08:12:00Z',
              likes: 1,
              replies: [],
            },
          ],
        },
      ],
      messages: [
        {
          id: '1',
          user: {
            username: 'mboughsn',
            image: require('../assets/data/sonamdp.png'),
          },
          lastMessage: 'Let’s meet for coffee ☕️',
          time: '20m',
          unread: true,
        },
        {
          id: '2',
          user: {username: 'me', image: require('../assets/CodeBuilder.jpeg')},
          lastMessage: 'Sure! When and where?',
          time: '19m',
          unread: false,
        },
        {
          id: '3',
          user: {
            username: 'mboughsn',
            image: require('../assets/data/sonamdp.png'),
          },
          lastMessage: 'I’ll text you the details.',
          time: 'now',
          unread: false,
        },
      ],
    },
  ];
  
  export const currentUser = {
    id: 10,  // Special ID for current user
    name: 'AppsAndGamesInc',
    username: 'apps&games',
    profile: require('../assets/CodeBuilder.jpeg'),
    // ... other user fields
  };

  export const reelsData = [
    {
      id: '1',
      username: 'travel_enthusiast',
      userImage: 'https://randomuser.me/api/portraits/women/44.jpg',
      videoUrl: require('../../src/assets/reels/reel1.mp4'),
      caption: 'Exploring the beautiful beaches of Bali! 🏖️ #travel #bali',
      likes: 1243,
      comments: 56,
      isLiked: false,
      musicName: 'Ocean Waves - Soundtrack',
    },
    {
      id: '2',
      username: 'foodie_adventures',
      userImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      videoUrl: require('../../src/assets/reels/reel2.mp4'),
      caption: 'Homemade pasta from scratch! 🍝 #foodie #cooking',
      likes: 892,
      comments: 34,
      isLiked: true,
      musicName: 'Italian Restaurant Ambience',
    },
    {
      id: '3',
      username: 'fitness_motivation',
      userImage: 'https://randomuser.me/api/portraits/women/68.jpg',
      videoUrl: require('../../src/assets/reels/reel3.mp4'),
      caption: 'Morning workout routine! Day 45 💪 #fitness #workout',
      likes: 2456,
      comments: 128,
      isLiked: false,
      musicName: 'Pump Up - Workout Music',
    },
    {
      id: '4',
      username: 'travel_enthusiast',
      userImage: 'https://randomuser.me/api/portraits/women/44.jpg',
      videoUrl: require('../../src/assets/reels/reel4.mp4'),
      caption: 'Exploring the beautiful beaches of Bali! 🏖️ #travel #bali',
      likes: 1243,
      comments: 56,
      isLiked: false,
      musicName: 'Ocean Waves - Soundtrack',
    },
    {
      id: '5',
      username: 'foodie_adventures',
      userImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      videoUrl: require('../../src/assets/reels/reel5.mp4'),
      caption: 'Homemade pasta from scratch! 🍝 #foodie #cooking',
      likes: 892,
      comments: 34,
      isLiked: true,
      musicName: 'Italian Restaurant Ambience',
    },
    {
      id: '6',
      username: 'fitness_motivation',
      userImage: 'https://randomuser.me/api/portraits/women/68.jpg',
      videoUrl: require('../../src/assets/reels/reel6.mp4'),
      caption: 'Morning workout routine! Day 45 💪 #fitness #workout',
      likes: 2456,
      comments: 128,
      isLiked: false,
      musicName: 'Pump Up - Workout Music',
    },
    {
      id: '7',
      username: 'travel_enthusiast',
      userImage: 'https://randomuser.me/api/portraits/women/44.jpg',
      videoUrl: require('../../src/assets/reels/reel7.mp4'),
      caption: 'Exploring the beautiful beaches of Bali! 🏖️ #travel #bali',
      likes: 1243,
      comments: 56,
      isLiked: false,
      musicName: 'Ocean Waves - Soundtrack',
    },
  ];
  
  export const searchItems = [
    {
      id: '1',
      image:
        'https://www.familyfoodonthetable.com/wp-content/uploads/2015/06/Weekend-food.png',
      username: 'travel_enthusiast',
      tags: ['travel', 'adventure', 'nature'],
      type: 'image',
      likes: 1243,
      comments: 56,
    },
    {
      id: '2',
      image:
        'https://www.candorblog.com/wp-content/uploads/2017/05/travel-022.jpg',
      username: 'foodie_adventures',
      tags: ['food', 'cooking', 'recipe'],
      type: 'video',
      likes: 892,
      comments: 34,
    },
    {
      id: '3',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyTTYGRHC1ANlXZbFSb42peuqGQsu7JstwAg&s',
      username: 'fitness_motivation',
      tags: ['fitness', 'workout', 'gym'],
      type: 'image',
      likes: 2456,
      comments: 128,
    },
    {
      id: '4',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStOpIPabPtKeOU0xeNEQido_jcxO4DdFEuOw&s',
      username: 'travel_enthusiast',
      tags: ['travel', 'adventure', 'nature'],
      type: 'image',
      likes: 1243,
      comments: 56,
    },
    {
      id: '5',
      image:
        'https://www.eatright.org/-/media/images/eatright-landing-pages/physicalactivitylp_804x482.jpg?as=0&w=967&rev=49578a5889d64349a3cc68b2ac762e43&hash=7E56938D92292108240175617FC67FE4',
      username: 'foodie_adventures',
      tags: ['food', 'cooking', 'recipe'],
      type: 'video',
      likes: 892,
      comments: 34,
    },
    {
      id: '6',
      image:
        'https://fitnesscfgyms.com/wp-content/uploads/2021/10/fitness-center.jpeg',
      username: 'fitness_motivation',
      tags: ['fitness', 'workout', 'gym'],
      type: 'image',
      likes: 2456,
      comments: 128,
    },
    {
      id: '7',
      image:
        'https://fitnesscfgyms.com/wp-content/uploads/2021/10/fitness-center.jpeg',
      username: 'travel_enthusiast',
      tags: ['travel', 'adventure', 'nature'],
      type: 'image',
      likes: 1243,
      comments: 56,
    },
    {
      id: '8',
      image:
        'https://media.self.com/photos/61bcd0e05aed92fc4251b026/4:3/w_2560%2Cc_limit/GettyImages-1213234926.jpeg',
      username: 'foodie_adventures',
      tags: ['food', 'cooking', 'recipe'],
      type: 'video',
      likes: 892,
      comments: 34,
    },
    {
      id: '9',
      image:
        'https://cdn.shopify.com/s/files/1/0561/9253/2651/files/InlineImage1.jpg?v=1628756402',
      username: 'fitness_motivation',
      tags: ['fitness', 'workout', 'gym'],
      type: 'image',
      likes: 2456,
      comments: 128,
    },
    ,
    {
      id: '10',
      image: 'https://www.acubody.net/wp-content/uploads/2021/09/Fitness-Day.jpg',
      username: 'travel_enthusiast',
      tags: ['travel', 'adventure', 'nature'],
      type: 'image',
      likes: 1243,
      comments: 56,
    },
    {
      id: '11',
      image:
        'https://cdn.shopify.com/s/files/1/0561/9253/2651/files/InlineImage1.jpg?v=1628756402',
      username: 'foodie_adventures',
      tags: ['food', 'cooking', 'recipe'],
      type: 'video',
      likes: 892,
      comments: 34,
    },
    {
      id: '12',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTapxVKtSe88mhTgvvBxJFrKx-Wp-MBd6ZdOQ&s',
      username: 'fitness_motivation',
      tags: ['fitness', 'workout', 'gym'],
      type: 'image',
      likes: 2456,
      comments: 128,
    },
    {
      id: '13',
      image:
        'https://fitnesscfgyms.com/wp-content/uploads/2021/10/fitness-center.jpeg',
      username: 'fitness_motivation',
      tags: ['fitness', 'workout', 'gym'],
      type: 'image',
      likes: 2456,
      comments: 128,
    },
    {
      id: '9',
      image:
        'https://cdn.shopify.com/s/files/1/0561/9253/2651/files/InlineImage1.jpg?v=1628756402',
      username: 'fitness_motivation',
      tags: ['fitness', 'workout', 'gym'],
      type: 'image',
      likes: 2456,
      comments: 128,
    },
    {
      id: '11',
      image:
        'https://cdn.shopify.com/s/files/1/0561/9253/2651/files/InlineImage1.jpg?v=1628756402',
      username: 'foodie_adventures',
      tags: ['food', 'cooking', 'recipe'],
      type: 'video',
      likes: 892,
      comments: 34,
    },
  ];
  
  export const typeData = [
    {id: 1, image: require('../assets/icon/GridIcon.png'), imageFocused: require('../assets/focusedGridIcon.png')},
    {id: 2, image: require('../assets/footer/reel.png'), imageFocused: require('../assets/focusedReel.png')},
    {id: 3, image: require('../assets/icon/TagsIcon.png'), imageFocused: require('../assets/focusedTagsIcon.png')},
  ];